aliases:
  - &xcode
    language: objective-c
    script: script/cibuild "$TRAVIS_XCODE_PROJECT" "$TRAVIS_XCODE_SCHEME" "build-for-testing test-without-building"
    xcode_project: Schemata.xcodeproj
  - &xcode10.2
    <<: *xcode
    osx_image: xcode10.2
  - &macOS
    xcode_scheme: Schemata (macOS)
  - &iOS
    xcode_scheme: Schemata (iOS)

os: osx
      
before_install:
  - brew install swiftformat
  - brew install swiftlint

branches:
  only:
    - master

matrix:
  include:
    - <<: *xcode10.2
      <<: *macOS
    - <<: *xcode10.2
      <<: *iOS
    - <<: *xcode10.2
      script: swift test
    - <<: *xcode10.2
      script: ./Carthage/Checkouts/Standards/test

notifications:
  email: false
